name: Grade Calculator

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:
  workflow_run:
    workflows: ["Sync to Solutions"]
    types:
      - completed
    branches: [solutions]


jobs:
  calculate-grade:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test-module:
          - 00_class_basics
          - 10_oop_encapsulation
          - 20_oop_inheritance

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests for ${{ matrix.test-module }}
        run: |
          uv run pytest ${{ matrix.test-module }}
