name: Grade Calculator

on:
  push:
    branches-ignore:
      - "main"
  workflow_dispatch:


jobs:
  calculate-grade:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.22"

      - name: Install dependencies
        run: |
          uv sync

      - name: Run tests for 00_class_basics
        run: |
          uv run pytest 00_class_basics

      - name: Run tests for 10_oop_encapsulation
        run: |
          uv run pytest 10_oop_encapsulation

      - name: Run tests for 20_oop_inheritance
        run: |
          uv run pytest 20_oop_inheritance
